#ifndef KOSHI8BIT_EASY_LIVING_GLOBAL_H
#define KOSHI8BIT_EASY_LIVING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KOSHI8BIT_EASY_LIVING_LIBRARY)
#define KOSHI8BIT_EASY_LIVING_EXPORT Q_DECL_EXPORT
#else
#define KOSHI8BIT_EASY_LIVING_EXPORT Q_DECL_IMPORT
#endif

#endif // KOSHI8BIT_EASY_LIVING_GLOBAL_H
